---
title: Converting an odds ratio to a risk difference
author: TP and RK
date: 2023-11-17
format:
  html:
    self-contained: true
---

```{css}
#| echo: false
@import url(https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css);
code { font-family: 'Fira Code', monospace; }
```

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
library(gtsummary)
library(DescTools)
```

Simulate a genotype `g` and an outcome `y`
```{r}
set.seed(12345)
n <- 1e5
minor_allele_freq <- 0.15
genotype <- rbinom(n, 2, minor_allele_freq)
logitp <- -4 + log(1.5)*genotype
p <- plogis(logitp)
y <- rbinom(n, 1, p)
```

```{r}
prop.table(table(genotype))
prop.table(table(y))
table(genotype, y)
prop.table(table(genotype, y))
prop.table(table(genotype, y), margin = 1)
prop.table(table(genotype, y), margin = 2)
```

Logistic regression - check simulated OR of ~1.5
```{r}
logreg <- glm(y ~ genotype, family = binomial)
oddsratio <- exp(coef(logreg)[2])
names(oddsratio) <- "Odds ratio"
print(oddsratio)
tbl_regression(logreg, exponentiate = TRUE)
```

Risk difference
```{r}
rdreg <- glm(y ~ genotype, family = binomial(link = "identity"))
summary(rdreg)
tbl_regression(rdreg, estimate_fun = function(x) style_sigfig(x, digits = 6))
p0 <- coef(rdreg)[1]
rdiff <- coef(rdreg)[2]
p1 <- rdiff + p0
res0 <- c(p0, p1, rdiff)
names(res0) <- c("p0", "p1", "Risk difference")
print(res0)
```

Formula from [Stack Exchange](https://stats.stackexchange.com/questions/324410/converting-odds-ratio-to-percentage-increase-reduction)
```{r}
pt <- (oddsratio * p0)/(1 + (oddsratio * p0) - p0)
results <- c(p0, pt, pt - p0, pt / p0)
names(results) <- c("p_0", "p_t", "Risk difference", "Risk ratio")
print(results)
```

Check OR to RR conversion with DescTools

```{r}
ORToRelRisk(oddsratio, p0)
```
